package sv.com.mined.sieni.controller;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author francisco_medina
 */
public class detPantallas {
    
		String json1 = "MTO_CLAS{MTO_PROG_CLAS,MTO_PLANT_CLAS,MTO_CLAS}";
		String json2 = "{MTO_PROG_CLAS{CON_PROG_CLAS{DOC,TIP,ESTD,TEMA,HOR,HRIO,TIPO_PUBLICA,ACC{CON_CLAS,CON_PLANT_CLAS,MOD_PROG_CLAS,ELI_CLAS},(CRE,REFRSH,AYUD)},"
				+ "CRE_PROG_CLAS{DOC&,TIP,ESTD&,TEMA,HOR,HRIO,TIPO_PUBLICA},(CRE,LIMP,CANC,AYUD)},"
				+ "MOD_PROG_CLAS{DOC&,TIP,ESTD,TEMA,HOR,HRIO,TIPO_PUBLICA},(GUAR,CANC,AYUD)}}"

				+ "MTO_PLANT_CLAS{CON_PLANT_CLAS{DOC,TITU,LIST_ELEM{ORDN,TIPO,MOST_TIPO%SI,NO%},ACC{CON_CLAS,MOD_PLANT_CLAS,ELI_PLANT_CLAS},(CRE,REFRSH,AYUD)},"
				+ "CRE_PLANT_CLAS{DOC&,TITU,LIST_ELEM{ORDN,TIPO,MOSTR_TIPO%SI,NO%},(CRE,LIMP,CANC,AYUD)}},"
				+ "MOD_PLANT_CLAS{DOC&,TITU,LIST_ELEM{ORDN,TIPO,MOSTR_TIPO%SI,NO%},(GUAR,CANC,AYUD)}}"

				+ "MTO_CLAS{CON_CLAS{DOC,PLANT,ESTD,ACC{MOD,ELI,CON_PROG_CLAS},(CRE,REFRSH,AYUD)},"
				+ "CRE_CLAS{DOC&,PLANT,ESTD,CONTEN,LIST_COMPONENT{NOMBR,TIPO%TXT,FORMUL,IMG,VID,SON,EVAL%,VALOR,CONFIG{TXT{TAMAÑO,FUENTE,NEGRIT,POSX,POSY,POSZ},IMG{ALTO,ANCHO,POSX,POSY,POSZ},VID{ALTO,ANCHO,VOL,POSX,POSY,POSZ},SON{VOL},INTERAC{LIST{EVNT,ACC,COMPONENT_SIG,COMPONENT_SIG_ACC,COMPONENT_SIG_DELAY}}}},(PREVIW,CRE,LIMP,CANC,AYUD,CON_EVAL,CON_AMULTIM)},"
				+ "MOD_CLAS{DOC&,PLANT&,ESTD,CONTEN,LIST_COMPONENT{NOMBR,TIPO%TXT,FORMUL,IMG,VID,SON,EVAL%,VALOR,CONFIG{TXT{TAMAÑO,FUENTE,NEGRIT,POSX,POSY,POSZ},IMG{ALTO,ANCHO,POSX,POSY,POSZ},VID{ALTO,ANCHO,VOL,POSX,POSY,POSZ},SON{VOL},INTERAC{LIST{EVNT,ACC,COMPONENT_SIG,COMPONENT_SIG_ACC,COMPONENT_SIG_DELAY}}}},(PREVIW,GUAR,LIMP,CANC,AYUD,CON_EVAL,CON_AMULTIM)},"

				+ "CLAS{CON_CLAS{DOC,PLANT,ESTD,ACC{RECIB},(REFRSH,AYUD)}*,"
				+ "RECIB_CLAS{DOC&,CONTEN,PUNTUACION(CONTINUAR,COMENZAR,SALIR,AYUD)}}*"

				+ "BUZON_CONSLTS{CON_CONSLTS{USR,TITU,ESTD,CURS,MOSTR_DOCLEIDOS%SI,NO%#,MOSTR_ALUMNLEIDOS%SI,NO%#,ACC{MOD,ELI}#,(CRE,REFRSH,AYUD)}},"
				+ "CRE_CONSLTS{USR&,TITU,ESTD&,CURS,LIST_MSJ{USR,TIPO%TXT,SON,VID,IMG,IMGCAM%,MSJ{TXT,IMGCAM,IMG,SON,VID},MOSTR_DOCLEIDOS%SI,NO%#,MOSTR_ALUMNLEIDOS%SI,NO%#},(CRE,CANC,AYUD)}},"
				+ "RESP_CONSLTS{USR&,TITU&,ESTD$,CURS&,LIST_MSJ{USR,TIPO%TXT,SON,VID,IMG,IMGCAM%,MSJ{TXT,IMGCAM,IMG,SON,VID},MOSTR_DOCLEIDOS%SI,NO%#,MOSTR_ALUMNLEIDOS%SI,NO%#},(RESP,CANC,AYUD)}}"

				+ "PORTAL_CONSLTS{TITU,ESTD,CURS,NUMMSJNOLEID,LIST_LEIDOPOR{USR,FECH,HOR},(CRE,REFRSH,AYUD)}},"
				+ "CONSLTS{TITU,ESTD,CURS,NUMMSJNOLEID,(CRE,REFRSH,AYUD)}},"

				+ "MTO_NOTIC{CON_NOTIC{DOC,TITU,TIPO%INFO,URGENTE,ADVERTENCIA%,ESTD,CURS,ACC{MOD,ELI},(CRE,REFRSH,AYUD)},"
				+ "CRE_NOTIC{DOC&,TITU,TIPO%INFO,URGENTE,ADVERTENCIA%,ESTD,CURS,ACC{MOD,ELI},(CRE,REFRSH,AYUD)},"
				+ "RESP_NOTIC{DOC&,TITU,TIPO%INFO,URGENTE,ADVERTENCIA%,ESTD,CURS,ACC{MOD,ELI},(GUARD,REFRSH,AYUD)}}"

				+ "PORTAL_NOTIC{TITU,TIPO,CURS,(REFRSH,AYUD)}}";

		String json3 = "{MTO_PLANT_CLAS{CON_PLAN_CLAS}}";
		String simb = "% valores posibles, & readonly, $modificable por creador o admin, () botones, # no alumnos, * SOLO ALUMNOS";
}
